# Generated by Django 6.0 on 2026-01-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_topheader1_topheader2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
