# Generated by Django 6.0 on 2026-01-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_herosectionbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectionbutton',
            name='button_link',
            field=models.CharField(max_length=255),
        ),
    ]
