# Generated by Django 6.0 on 2026-01-17 06:05

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='review_profile_images/')),
                ('name', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMapReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='review_photos/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.googlemapreview')),
            ],
        ),
    ]
