# Generated by Django 6.0 on 2026-01-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_googlemapreview_googlemapreviewphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemapreview',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
