# Generated by Django 6.0 on 2026-01-17 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_googlemapreview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemapreview',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
