# Generated by Django 6.0 on 2026-01-17 07:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_googlemapreview_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='partner_logos/')),
            ],
        ),
    ]
