# Generated by Django 6.0 on 2025-12-27 16:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytopress',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_images/'),
        ),
    ]
