# Generated by Django 6.0 on 2025-12-26 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_readytopress_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytopress',
            name='size',
            field=models.CharField(choices=[('SM', 'SMALL'), ('MD', 'MEDIUM'), ('LG', 'LARGE'), ('XL', 'XLARGE'), ('XXL', 'XXLARGE')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
