# Generated by Django 6.0 on 2025-12-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_readytopress_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytopress',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='readytopress',
            name='size',
        ),
    ]
