# Generated by Django 6.0 on 2026-01-17 11:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.customdesign')),
            ],
        ),
    ]
